ESTADO_CIVIL_SOLTERO = 'S';
ESTADO_CIVIL_CASADO = 'C';
ESTADO_CIVIL_DIVORCIADO = 'D';
ESTADO_CIVIL_VIUDO = 'V';

SEXO_MASCULINO = 'M';
SEXO_FEMENINO = 'F';

NINGUNA = 'N';

ASEGURADORA_IPS = 'I';
ASEGURADORA_SERMED = 'S';
ASEGURADORA_UNIMED = 'U';
ASEGURADORA_MIGONE = 'M';


TIPOS_DOSIS = 1;
TIPOS_FRECUENCIA = 2;
TIPOS_DURACION = 3;

SITUACION_ACTIVO = 1;
SITUACION_INACTIVO = 0;

PAGINATION_ARCHIVO_NEXT = 5;
PAGINATION_HISTORIA_NEXT = 5;
