ESTADO_CIVIL_SOLTERO = 'S';
ESTADO_CIVIL_CASADO = 'C';
ESTADO_CIVIL_DIVORCIADO = 'D';
ESTADO_CIVIL_VIUDO = 'V';

SEXO_MASCULINO = 'M';
SEXO_FEMENINO = 'F';

NINGUNA = 'N';

ASEGURADORA_IPS = 'I';
ASEGURADORA_SERMED = 'S';
ASEGURADORA_UNIMED = 'U';
ASEGURADORA_MIGONE = 'M';
